# ansible-playbook -i localhost,\ -e {"instances":["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment","frontend"]}" roboshop.yaml
- name: create ec2 instance and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-0dde2b2dbc55696ae
    ami_id: ami-0220d79f3f480ecf5
    subnet_id: subnet-05f89af555de452f2
    domain_name: "sujju.online"
    env: dev
    action: create
    instances:
       - mongodb
       - catalogue 
       - redis
       - user
       - cart
       - mysql
       - shipping
       - rabbitmq
       - payment
       - frontend
###create###
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        instance_type: "t2.micro"
        security_group: "{{ sg_id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        image_id: "{{ ami_id }}"
        region: us-east-1
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}" 
      register: ec2_output

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"

    - name: create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}-{{ env }}.{{ domain_name }}" #mongodb-dev.sujju.online frontend-dev.sujju.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
      loop: "{{ ec2_output.results }}" #list

    - name: create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "roboshop-{{ item.item }}-{{ env }}.{{ domain_name }}" #roboshop-dev.sujju.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true 
      loop: "{{ ec2_output.results }}"
      when: item.item == "frontend" 

    
