- name: create ec2 instance (maddali boss)
  hosts: localhost
  connection: local

  vars:
    sg_id: sg-0dde2b2dbc55696ae
    ami_id: ami-0220d79f3f480ecf5
    subnet_id: subnet-05f89af555de452f2
    env: dev
    instances:
      - mongodb
      - catalogue

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        instance_type: "t3.micro"
        security_group_ids:
          - "{{ sg_id }}"
        vpc_subnet_id: "{{ subnet_id }}"
        image_id: "{{ ami_id }}"
        region: ap-south-1
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: print the output
      ansible.builtin.debug:
        var: ec2_output