- name: configure frontend
  hosts: frontend
  become: yes
  tasks:
  - name: enable nginx 1.24 module
    ansible.builtin.shell: |
      dnf module reset nginx -y
      dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: copy roboshop nginx config
    ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/conf.d/roboshop.conf
      validate: "nginx -t -c %s"
    notify: restart nginx

  - name: ensure html directory exists
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend content
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: extract frontend content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  handlers:
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted