[mongodb]
mongodb-dev.sujju.online

[catalogue]
catalogue-dev.sujju.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.sujju.online
CATALOGUE_HOST=catalogue-dev.sujju.online
REDIS_HOST=redis-dev.sujju.online
USER_HOST=user-dev.sujju.online

