- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes 

  - name: check if root password is set
    ansible.builtin.command: mysql -uroot -pRoboShop@1 -e 'show databases;'
    ignore_errors: true                                           
    register: mysql_check 
  
  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
    when: mysql_check.rc != 0
    